services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: activity_workspace_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - DEFAULT_STORAGE_PATH=/storage_mounts/rom1
    volumes:
      - /mnt:/storage_mounts
